const INTRO_LINES=['照片記錄了我們想留下的瞬間。','朋友、家人、學校、去過的地方……','我們拍下它們，也分享它們。','但當一張照片離開你的手中，\n你還知道它會去到哪裡嗎？','有些資訊從來沒有消失。','它們只是散落在不同的地方，\n等待被重新拼起來。','而最近，\n城市裡開始出現一些奇怪的照片……','《NULL》','第一章'];

export class GuidanceManager {
  constructor({gameState,saveManager,view,getMode,onIntroComplete,scenes=[]}){this.gameState=gameState;this.saveManager=saveManager;this.view=view;this.getMode=getMode;this.onIntroComplete=onIntroComplete;this.scenes=scenes;this.introIndex=0;this.modalOpen=false;this.pendingNotice=null;}
  startIntro(){this.introIndex=0;this.renderIntro();}
  renderIntro(){this.view.openIntro(INTRO_LINES[this.introIndex],this.introIndex,INTRO_LINES.length,{onContinue:()=>this.nextIntro(),onSkip:()=>this.finishIntro()});}
  nextIntro(){if(this.introIndex<INTRO_LINES.length-1){this.introIndex+=1;this.renderIntro();return;}this.finishIntro();}
  finishIntro(){this.gameState.set('flags.storyIntroductionSeen',true);this.saveManager.save();this.view.closeIntro();this.onIntroComplete?.();}
  openControls({automatic=false,battle=false}={}){if(this.modalOpen)return;this.modalOpen=true;this.gameState.set('playerMovementLocked',true);if(automatic)this.gameState.set(`flags.${battle?'battleTutorialSeen':'controlsTutorialSeen'}`,true);this.saveManager.save();this.view.openControls({battle,onClose:()=>this.closeModal()});}
  openJournal(){if(this.modalOpen)return;this.modalOpen=true;this.gameState.set('playerMovementLocked',true);const groups=this.journal();const boardQuest=this.noticeBoardSideQuest();if(boardQuest)groups[boardQuest.completed?'completed':'side'].push(boardQuest);this.view.openJournal(groups,()=>this.closeModal());}
  closeModal(){this.modalOpen=false;this.view.closeModal();if(this.getMode?.()==='EXPLORATION')this.gameState.set('playerMovementLocked',false);this.saveManager.save();this.flushNotice();}
  onExploration(sceneId){this.syncMainQuest(sceneId);if(sceneId==='home_map'&&!this.gameState.get('flags.controlsTutorialSeen')){this.openControls({automatic:true});return;}this.flushNotice();}
  onBattle(enemyId){if(['sharer','tracker'].includes(enemyId)&&!this.gameState.get('flags.battleTutorialSeen'))this.openControls({automatic:true,battle:true});}
  discoverRin(){const completed=Boolean(this.gameState.get('sideQuests.rinPhotoInspection.completed'));const accepted=Boolean(this.gameState.get('sideQuests.rinPhotoInspection.accepted'));this.gameState.set('sideQuests.rinPhotoInspection.discovered',true);this.gameState.set('sideQuests.rinPhotoInspection.status',completed?'COMPLETED':accepted?'ACTIVE':'AVAILABLE');this.gameState.set('sideQuests.rinPhotoInspection.currentStage',completed?'completed':accepted?'inspect_photos':'talk_to_rin');this.saveManager.save();}
  syncMainQuest(sceneId=this.gameState.get('sceneId')){let quest=this.currentMain(sceneId);if(quest.id==='talk_parent_after_album')quest={...quest,title:sceneId==='home_map'?'和 PARENT 談談':'回到家中',objective:sceneId==='home_map'?'和 PARENT 談談。':'回家。'};const previous=this.gameState.get('quests.ch1_guidance.currentStage');this.gameState.set('quests.ch1_guidance',{discovered:true,status:quest.completed?'COMPLETED':'ACTIVE',currentStage:quest.id,objective:quest.objective,progress:quest.progress??0,maxProgress:quest.maxProgress??1,completed:quest.completed});this.saveManager.save();if(previous&&previous!==quest.id&&!quest.completed)this.queueNotice(quest.objective);return quest;}
  noticeBoardSideObjective(sceneId){const scene=this.scenes.find((item)=>item.id===sceneId);const count=(scene?.entities??[]).filter((entity)=>entity.interaction?.noticeBoard).length;if(!count)return null;const state=this.gameState.get(`noticeBoardState.${sceneId}`)??{};if(!state.firstDiscoveryTriggered)return'調查附近的公布欄，看看照片和公告中留下了什麼。';if(count>1&&!state.secondDiscoveryTriggered)return'再看看附近其他的公告，也許能發現不同的線索。';return null;}
  noticeBoardObjective(){return null;}
  noticeBoardSideQuest(sceneId=this.gameState.get('sceneId')){const scene=this.scenes.find((item)=>item.id===sceneId);const count=(scene?.entities??[]).filter((entity)=>entity.interaction?.noticeBoard).length;if(!count)return null;const objective=this.noticeBoardSideObjective(sceneId);return{title:'公布欄調查',description:'看看照片與公告在環境中留下了哪些片段。',objective:objective??'這個區域的公布欄已調查完成。',completed:objective===null};}
  currentMain(sceneId=this.gameState.get('sceneId')){const flag=(name)=>Boolean(this.gameState.get(`flags.${name}`));const noticeObjective=this.noticeBoardObjective(sceneId);if(flag('ch1Complete'))return{id:'chapter_complete',title:'第一章',description:'你完成了這段關於照片、分享與界線的旅程。',objective:'第一章已完成。',completed:true};if(flag('albumBattleComplete')||flag('albumAwaitingParent'))return{id:'talk_parent_after_album',title:'回到家中',description:'ALBUM 已經平靜下來。回家和 PARENT 談談。',objective:'回到家中和 PARENT 對話。'};if(flag('albumPhase2Complete'))return{id:'face_final_layer',title:'相簿房間',description:'ALBUM 還留下最後一層資料拼圖。',objective:'繼續面對 ALBUM。'};if(flag('albumPhase1Complete'))return{id:'face_exposure',title:'相簿房間',description:'回憶之後，照片的曝光仍在擴散。',objective:'繼續面對 ALBUM。'};if(flag('albumRoomUnlocked'))return{id:'enter_album_room',title:'通往相簿房間',description:'PHOTO KEEPER 已經打開前往深處的道路。',objective:'前往相簿房間。'};if(flag('memoryGalleryInvestigated'))return{id:'return_keeper',title:'回憶畫廊',description:'三組回憶都已經看過。',objective:'回去和 PHOTO KEEPER 談談。'};if(sceneId==='memory_gallery')return{id:'inspect_memories',title:'回憶畫廊',description:'畫廊裡散落著熟悉的照片。',objective:noticeObjective??'調查畫廊中的回憶照片。'};if(['album_town','data_world'].includes(sceneId)){const stage=this.gameState.get('quests.ch1_album_path.stageId');if(stage==='meet_album_allies')return{id:'album_allies',title:'不同的分享觀點',description:'你已經聽過幾種看待照片分享的方式。',objective:'繼續調查照片留下的線索。'};if(stage==='find_privacy_clue'||stage==='complete_photo_check')return{id:'album_clues',title:'照片留下的線索',description:'資料世界裡散落著照片帶來的資訊。',objective:'調查照片並完成照片檢查。'};return{id:'meet_keeper',title:'陌生的資料世界',description:'熟悉的照片變成了陌生的景象。',objective:'尋找能說明這裡狀況的人。'};}if(['school_front','school_interior'].includes(sceneId))return{id:'school_clues',title:'校園裡的照片',description:'奇怪的照片一路延伸到學校。',objective:noticeObjective??'在學校尋找 KAI 與其他線索。'};if(sceneId==='photo_street')return{id:'strange_photos',title:'奇怪的照片',description:'街道上出現了不自然的照片痕跡。',objective:noticeObjective??'沿著照片痕跡前往學校。'};if(sceneId==='neighborhood')return{id:'go_neighborhood',title:'離開家門',description:'家門外的街道似乎和平常不太一樣。',objective:noticeObjective??'前往社區街道。'};if(['photo_choice_ask_first','photo_choice_family_only','photo_choice_post_now'].some((id)=>flag(id)))return{id:'leave_home',title:'離開家門',description:'你和 PARENT 已經談過照片分享的事情。',objective:'從家門前往社區。'};return{id:'talk_parent',title:'家中的照片',description:'PARENT 正準備分享一張照片。',objective:'和 PARENT 對話。'};}
  journal(){const main=this.currentMain();const groups={main:[],side:[],partners:[],completed:[]};groups[main.completed?'completed':'main'].push(main);if(this.gameState.get('sideQuests.rinPhotoInspection.discovered')){const side=this.gameState.get('sideQuests.rinPhotoInspection')??{};const completed=side.status==='COMPLETED'||side.completed;groups[completed?'completed':'side'].push({title:'RIN 的照片檢查',description:'RIN 正準備挑選一些照片分享出去。幫她看看照片中是否藏著容易被忽略的資訊。',objective:side.currentStage==='return_to_rin'?'回去和 RIN 談談。':side.status==='ACTIVE'?'檢查 RIN 準備分享的照片。':'和 RIN 談談。',completed});}const partnerDetails={kai:'喜歡快速分享有趣照片的同學。',rin:'正在重新整理照片分享方式的同學。',mio:'會留意照片內容與分享範圍的同學。',photo_kid:'在資料世界收集照片線索的夥伴。',photo_keeper:'守護回憶畫廊與照片入口的夥伴。'};const partnerNames={kai:'KAI',rin:'RIN',mio:'MIO',photo_kid:'PHOTO KID',photo_keeper:'PHOTO KEEPER'};for(const id of this.gameState.get('partners.knownIds')??[])if(partnerNames[id])groups.partners.push({title:partnerNames[id],description:partnerDetails[id],partner:true});return groups;}
  queueNotice(objective){this.pendingNotice=objective;this.flushNotice();}
  flushNotice(){if(!this.pendingNotice||this.modalOpen||['DIALOGUE','BATTLE','PUZZLE','REFLECTION'].includes(this.getMode?.()))return;const text=this.pendingNotice;this.pendingNotice=null;this.view.showNotification(text);}
}
