export class PuzzleManager {
  constructor({puzzles,gameState,view,saveManager,onStart,onComplete,onExit}){this.puzzles=puzzles;this.gameState=gameState;this.view=view;this.saveManager=saveManager;this.onStart=onStart;this.onComplete=onComplete;this.onExit=onExit;this.puzzle=null;this.context={};this.selected=new Set();this.attempts=0;this.photoIndex=0;this.photoAnswers={};this.photoRevealed=false;}
  start(id,context={}){this.puzzle=this.puzzles.find((item)=>item.id===id);if(!this.puzzle)throw new Error(`找不到解謎：${id}`);this.context={...context,puzzleId:id};const saved=this.gameState.get(`puzzleProgress.${id}`);this.selected=new Set(saved?.selected??[]);this.attempts=saved?.attempts??0;this.photoIndex=Math.min(saved?.photoIndex??0,Math.max(0,(this.puzzle.photos?.length??1)-1));this.photoAnswers=saved?.photoAnswers??{};this.onStart?.(this.context,this.puzzle);this.view.reset();if(this.isPhotoInspection())this.renderPhotoInspection();else{this.view.open(this.puzzle,this.selected,(spot)=>this.toggle(spot));if(saved?.completed)this.view.showSuccess(this.puzzle.battleModifiers);}}
  isPhotoInspection(){return this.puzzle?.presentation==='rin_photo_inspection';}
  renderPhotoInspection(feedback=''){this.photoRevealed=false;this.selected=new Set(this.photoAnswers[this.puzzle.photos[this.photoIndex].id]??[]);this.view.openPhotoInspection(this.puzzle,this.photoIndex,this.selected,(option)=>this.toggle(option),feedback);}
  toggle(id){if(this.isPhotoInspection()){if(this.photoRevealed)return;if(id==='none'){this.selected=this.selected.has('none')?new Set():new Set(['none']);}else{this.selected.delete('none');if(this.selected.has(id))this.selected.delete(id);else this.selected.add(id);}const photo=this.puzzle.photos[this.photoIndex];this.photoAnswers[photo.id]=[...this.selected];this.save(false);this.view.renderPhotoOptions(this.puzzle,this.photoIndex,this.selected,(option)=>this.toggle(option));return;}if(this.selected.has(id))this.selected.delete(id);else this.selected.add(id);this.view.renderHotspots(this.puzzle,this.selected,(spot)=>this.toggle(spot));this.save(false);}
  submit(){if(this.isPhotoInspection())return this.submitPhotoInspection();this.attempts+=1;const missing=this.puzzle.required.filter((id)=>!this.selected.has(id));if(missing.length){this.save(false);this.view.showFailure(missing.length);return false;}this.save(true);this.view.showSuccess(this.puzzle.battleModifiers);this.onComplete?.(this.puzzle,this.context);return true;}
  submitPhotoInspection(){const photo=this.puzzle.photos[this.photoIndex];if(!(this.photoAnswers[photo.id]?.length)){this.view.showPhotoPrompt('RIN：「再看一下吧，可以選擇一個或多個項目。」');return false;}if(!this.photoRevealed){this.photoRevealed=true;const labels=(photo.answers??[]).map((id)=>this.puzzle.options.find((option)=>option.id===id)?.label??id);const chosen=[...this.selected];const exact=chosen.length===photo.answers.length&&chosen.every((id)=>photo.answers.includes(id));this.view.showPhotoFeedback(photo.feedback,labels,exact,this.photoIndex===this.puzzle.photos.length-1);return true;}if(this.photoIndex<this.puzzle.photos.length-1){this.photoIndex+=1;this.save(false);this.renderPhotoInspection();return true;}this.save(true);this.view.showPhotoComplete();this.onComplete?.(this.puzzle,this.context);return true;}
  retry(){if(this.isPhotoInspection()){this.photoAnswers={};this.photoIndex=0;this.photoRevealed=false;this.save(false);this.renderPhotoInspection();return;}this.selected.clear();this.view.reset();this.view.renderHotspots(this.puzzle,this.selected,(spot)=>this.toggle(spot));this.view.showFailure(this.puzzle.required.length);this.save(false);}
  save(completed){const progress={completed,selected:[...this.selected],attempts:this.attempts,battleModifiers:completed?(this.puzzle.battleModifiers??[]):[]};if(this.isPhotoInspection()){progress.photoIndex=this.photoIndex;progress.photoAnswers=this.photoAnswers;progress.reviewedCount=Object.keys(this.photoAnswers).length;}this.gameState.set(`puzzleProgress.${this.puzzle.id}`,progress);this.saveManager.save();}
  exit(){const puzzle=this.puzzle;const context=this.context;const completed=Boolean(puzzle&&this.gameState.get(`puzzleProgress.${puzzle.id}`)?.completed);this.view.close();this.puzzle=null;this.context={};this.onExit?.(puzzle,context,completed);}
}
