import { canCharacterSeePost } from '../echo/EchoVisibility.js';

const AUDIENCES=new Set(['PUBLIC','FRIENDS','SELECTED','PRIVATE']);
const LOCATIONS=new Set(['CURRENT_LOCATION','GENERAL_AREA','NO_LOCATION']);
const TIMINGS=new Set(['SHARE_NOW','SHARE_LATER']);
const DISCLOSURE_FIELDS=new Set(['nickname','ageRange','platform','email','phone','school','birthday','gameId']);
const REWARDS=new Set(['coins','equipment','skin']);
const clone=(value)=>structuredClone(value);
const unique=(values)=>[...new Set((values??[]).filter((value)=>typeof value==='string'&&value.length))];

function read(source,path){if(source&&typeof source.get==='function')return source.get(path);return String(path).split('.').filter(Boolean).reduce((current,key)=>current?.[key],source);}
function allEchoRecords(source){const echo=read(source,'echo')??{};return [...(echo.posts??[]),...(echo.drafts??[])].filter(Boolean);}
function canonicalRecord(source,{idPath,sourceEventId}){const records=allEchoRecords(source);const id=idPath?read(source,idPath):null;return records.filter((record)=>(id&&record.id===id)||record.sourceEventId===sourceEventId).sort((a,b)=>(b.order??0)-(a.order??0))[0]??null;}

function normalizeRecord(record,fallback={}){
  if(!record&&!fallback.available)return null;
  const actual=record??fallback;const deleted=Boolean(actual.deleted||actual.status==='DELETED');const audience=AUDIENCES.has(actual.audience)?actual.audience:null;
  return{source:record?'echo':'legacy_flags',contentId:actual.contentId??fallback.contentId??null,sourceEventId:actual.sourceEventId??fallback.sourceEventId??null,caption:typeof actual.caption==='string'?actual.caption:null,taggedCharacters:unique(actual.taggedCharacters),location:LOCATIONS.has(actual.location)?actual.location:null,timing:TIMINGS.has(actual.timing)?actual.timing:null,audience,selectedAudience:audience==='SELECTED'?unique(actual.selectedAudience):[],status:deleted?'DELETED':actual.status??(actual.posted?'POSTED':null),posted:Boolean(actual.posted||actual.status==='POSTED'||deleted),deleted};
}

function legacyPhoto01(source){const location={current:'CURRENT_LOCATION',general:'GENERAL_AREA',none:'NO_LOCATION'}[read(source,'flags.act1LocationMode')];const timing={now:'SHARE_NOW',later:'SHARE_LATER'}[read(source,'flags.act1Timing')];return{available:Boolean(read(source,'flags.ch2Act1EchoDecided')||location||timing),contentId:'CH2-MIO-PHOTO-01',sourceEventId:'ch2_act1_mio_story',location,timing,audience:'FRIENDS',status:'POSTED',posted:true};}
function legacyPhoto02(source){const audience={public:'PUBLIC',friends:'FRIENDS',selected:'SELECTED',private:'PRIVATE'}[read(source,'flags.act2Audience')];return{available:Boolean(read(source,'flags.ch2Act2PostCompleted')||audience),contentId:'CH2-MIO-PHOTO-02',sourceEventId:'ch2_act2_mio_post',location:'NO_LOCATION',timing:'SHARE_NOW',audience,selectedAudience:read(source,'flags.act2SelectedAudience')??[],status:'POSTED',posted:true};}
function legacyGroupPhoto(source){const audience={public:'PUBLIC',friends:'FRIENDS',selected:'SELECTED',private:'PRIVATE'}[read(source,'flags.groupPhotoAudience')];const deleted=Boolean(read(source,'flags.postDeleted'));return{available:Boolean(read(source,'flags.ch2GroupPhotoPostCompleted')||audience||deleted),contentId:'CH2-GROUP-PHOTO-01',sourceEventId:'ch2_act3_group_post',location:'NO_LOCATION',timing:'SHARE_NOW',audience,selectedAudience:read(source,'flags.groupPhotoSelectedAudience')??[],status:deleted?'DELETED':'POSTED',posted:true,deleted};}

function optionalDisclosure(source){
  const categories=unique(read(source,'flags.surveyDataShared')).filter((field)=>DISCLOSURE_FIELDS.has(field));const first=read(source,'flags.firstReward')??read(source,'flags.surveyRewardType');const second=read(source,'flags.secondReward');const bonusAudience={public:'PUBLIC',friends:'FRIENDS',selected:'SELECTED',private:'PRIVATE'}[read(source,'flags.bonusShareAudience')]??null;
  return{rewardBooth:{discovered:Boolean(read(source,'flags.surveyDiscovered')),started:Boolean(read(source,'flags.surveyStarted')),cancelled:Boolean(read(source,'flags.surveyCancelled')),completed:Boolean(read(source,'flags.surveyCompleted')),providedCategories:categories,rewards:[first,second].filter((reward)=>REWARDS.has(reward)),bonusShare:{choice:read(source,'flags.bonusShareChoice')??null,completed:Boolean(read(source,'flags.bonusShareCompleted')),audience:bonusAudience,selectedAudience:bonusAudience==='SELECTED'?unique(read(source,'flags.bonusShareSelectedAudience')):[]}},lookingForMio:{eligible:Boolean(read(source,'flags.ch2LookingForMioEligible')),encountered:Boolean(read(source,'flags.mioFollowerEncountered')),response:read(source,'flags.ch2LookingForMioResponse')??null,reported:Boolean(read(source,'flags.mioFollowerReportedToMio')),resolved:Boolean(read(source,'flags.mioFollowerConsequenceComplete'))}};
}

function synthesizeFragments(snapshot){
  const fragments=[];const connections=[];const ids=new Set();const add=(fragment)=>{fragments.push(fragment);ids.add(fragment.id);return fragment.id;};const connect=(from,to,relation)=>{if(ids.has(from)&&ids.has(to))connections.push({from,to,relation});};
  const addPost=(source,post)=>{if(!post)return;const photo=add({id:`${source}.photo`,type:'PHOTO',source,value:post.contentId,explicit:true,optional:false});if(post.location&&post.location!=='NO_LOCATION')connect(photo,add({id:`${source}.location`,type:'LOCATION',source,value:post.location,explicit:true,optional:false}),'contains_explicit_location');if(post.timing)connect(photo,add({id:`${source}.timing`,type:'TIMING',source,value:post.timing,explicit:true,optional:false}),'has_sharing_timing');for(const characterId of post.taggedCharacters)connect(photo,add({id:`${source}.tag.${characterId}`,type:'TAG',source,value:characterId,explicit:true,optional:false}),'tags_character');if(post.audience)connect(photo,add({id:`${source}.audience`,type:'AUDIENCE',source,value:{mode:post.audience,selected:post.selectedAudience},explicit:true,optional:false}),'visible_to_audience');connect(photo,add({id:`${source}.persistence`,type:'POST_PERSISTENCE',source,value:{status:post.status,posted:post.posted,deleted:post.deleted},explicit:true,optional:false}),'has_current_post_state');};
  addPost('photo01',snapshot.photo01);addPost('photo02',snapshot.photo02);addPost('groupPhoto',snapshot.groupPhoto?.post);
  if(snapshot.groupPhoto?.post){const consent=add({id:'groupPhoto.consent',type:'CONSENT',source:'groupPhoto',value:{asked:snapshot.groupPhoto.consentAsked,preference:snapshot.groupPhoto.rinPreference},explicit:true,optional:false});connect('groupPhoto.photo',consent,'has_consent_context');if(snapshot.groupPhoto.repairAction)connect('groupPhoto.photo',add({id:'groupPhoto.repair',type:'REPAIR',source:'groupPhoto',value:snapshot.groupPhoto.repairAction,explicit:true,optional:false}),'has_repair_outcome');}
  const booth=snapshot.optionalDisclosure.rewardBooth;if(booth.completed&&booth.providedCategories.length){const disclosure=add({id:'rewardBooth.disclosure',type:'OPTIONAL_DISCLOSURE',source:'rewardBooth',value:booth.providedCategories,explicit:true,optional:true});if(booth.rewards.length)connect(disclosure,add({id:'rewardBooth.reward',type:'REWARD',source:'rewardBooth',value:booth.rewards,explicit:true,optional:true}),'associated_with_reward');}
  const looking=snapshot.optionalDisclosure.lookingForMio;if(looking.encountered)connect('photo01.photo',add({id:'photo01.contextualInference',type:'CONTEXTUAL_INFERENCE',source:'lookingForMio',value:{response:looking.response,reported:looking.reported,resolved:looking.resolved},explicit:false,optional:true}),'supported_real_world_inference');
  return{fragments,connections};
}

export function buildCh2FinalSnapshot(source){
  const photo01=normalizeRecord(canonicalRecord(source,{sourceEventId:'ch2_act1_mio_story'}),legacyPhoto01(source));const photo02=normalizeRecord(canonicalRecord(source,{idPath:'flags.act2PostId',sourceEventId:'ch2_act2_mio_post'}),legacyPhoto02(source));const groupPost=normalizeRecord(canonicalRecord(source,{idPath:'flags.groupPhotoPostId',sourceEventId:'ch2_act3_group_post'}),legacyGroupPhoto(source));const optional=optionalDisclosure(source);
  const snapshot={version:1,photo01,photo02:photo02?{...photo02,rinVisible:canCharacterSeePost(photo02,'rin',{friendIds:['mio','kai','rin']})}:null,groupPhoto:groupPost?{post:groupPost,consentAsked:read(source,'flags.consentAsked')??null,rinPreference:read(source,'flags.rinSharePreference')??null,conflict:{occurred:Boolean(read(source,'flags.consentConflict')),type:read(source,'flags.groupPhotoConflictType')??null,unresolved:Boolean(read(source,'flags.consentConflictUnresolved'))},repairAction:read(source,'flags.groupPhotoRepairChoice')??null}:null,optionalDisclosure:optional,consequence:{photo01Resolved:Boolean(read(source,'flags.ch2Act1ConsequenceResolved')),photo01Route:read(source,'flags.ch2ConsequenceRoute')??null}};
  return clone({...snapshot,...synthesizeFragments(snapshot)});
}
