const ASSET_ROOT='./assets/ui/ch2/boss/data-fragments/';
export const FRAGMENT_ASSETS=Object.freeze({PHOTO:`${ASSET_ROOT}CH2-BOSS-DATA-PHOTO.png`,TIME:`${ASSET_ROOT}CH2-BOSS-DATA-TIME.png`,LOCATION:`${ASSET_ROOT}CH2-BOSS-DATA-LOCATION.png`,TAG:`${ASSET_ROOT}CH2-BOSS-DATA-TAG.png`,AUDIENCE:`${ASSET_ROOT}CH2-BOSS-DATA-AUDIENCE.png`,SOCIAL_CONNECTION:`${ASSET_ROOT}CH2-BOSS-DATA-SOCIAL-CONNECTION.png`,MESSAGE:`${ASSET_ROOT}CH2-BOSS-DATA-MESSAGE.png`,BACKGROUND_CLUE:`${ASSET_ROOT}CH2-BOSS-DATA-BACKGROUND-CLUE.png`});
export const CH2_DATA_PROFILE_BALANCE=Object.freeze({BASE_STABILITY:80,MIN_PROFILE_STABILITY:80,MAX_PROFILE_STABILITY:150,EXPLICIT:{PHOTO:8,TIME:6,LOCATION:10,TAG:6,AUDIENCE:6,SOCIAL_CONNECTION:6,MESSAGE:4,BACKGROUND_CLUE:4},COMPLETED_CONNECTION:{PHOTO_TIME:5,PHOTO_LOCATION:7,PHOTO_TAG:5,PHOTO_BACKGROUND_CLUE:3,TAG_SOCIAL_CONNECTION:5,PHOTO_AUDIENCE:5},CONTEXTUAL_CONNECTION:2,DISRUPTION:{ISOLATED:4,CONTEXTUAL:5,COMPLETED:8}});
const TYPE_MAP=Object.freeze({PHOTO:'PHOTO',TIMING:'TIME',TIME:'TIME',LOCATION:'LOCATION',TAG:'TAG',AUDIENCE:'AUDIENCE',SOCIAL_CONNECTION:'SOCIAL_CONNECTION',MESSAGE:'MESSAGE',BACKGROUND_CLUE:'BACKGROUND_CLUE',CONTEXTUAL_INFERENCE:'BACKGROUND_CLUE'});
const PRIORITY=['PHOTO','TIME','LOCATION','TAG','AUDIENCE','SOCIAL_CONNECTION','MESSAGE','BACKGROUND_CLUE'];
const keyFor=(a,b)=>[a,b].sort().join('_');
const uniqueByType=(items)=>{const out=[];for(const item of items)if(!out.some(existing=>existing.type===item.type))out.push(item);return out;};

function normalizeFragments(snapshot,resolved){const merged=[...(resolved.fragments??[]),...(snapshot.fragments??[])];const out=[];for(const raw of merged){const type=TYPE_MAP[raw.type];if(!type||type==='SOCIAL_CONNECTION')continue;const item={id:raw.id,type,source:raw.source,value:raw.value,explicit:raw.explicit===true,optional:Boolean(raw.optional)};if(!out.some(x=>x.id===item.id))out.push(item);}return out;}
function addUnresolved(fragments,type,id){if(!fragments.some(item=>item.type===type))fragments.push({id,type,source:'inference',value:null,explicit:false,optional:true,state:'UNRESOLVED',unresolved:true});}
function resolveConnections(fragments,snapshot){const byId=new Map(fragments.map(item=>[item.id,item]));const pairs=[];const add=(fromId,toId,relation)=>{const from=byId.get(fromId),to=byId.get(toId);if(!from||!to||pairs.some(p=>p.fromId===fromId&&p.toId===toId))return;pairs.push({fromId,toId,fromType:from.type,toType:to.type,relation});};for(const link of snapshot.connections??[])add(link.from,link.to,link.relation);const photo=fragments.find(item=>item.type==='PHOTO'),background=fragments.find(item=>item.type==='BACKGROUND_CLUE'),location=fragments.find(item=>item.type==='LOCATION');if(photo&&background&&!pairs.some(p=>p.fromId===photo.id&&p.toId===background.id))pairs.push({fromId:photo.id,toId:background.id,fromType:'PHOTO',toType:'BACKGROUND_CLUE',relation:'contextual_background'});if(photo&&location&&!pairs.some(p=>p.fromId===photo.id&&p.toId===location.id))pairs.push({fromId:photo.id,toId:location.id,fromType:'PHOTO',toType:'LOCATION',relation:'inference_location'});const tag=fragments.find(item=>item.type==='TAG'&&item.explicit);if(tag){const social={id:'derived.socialConnection',type:'SOCIAL_CONNECTION',source:'canonical_tag_relation',value:null,explicit:true,optional:true};fragments.push(social);pairs.push({fromId:tag.id,toId:social.id,fromType:'TAG',toType:'SOCIAL_CONNECTION',relation:'tags_character'});}return pairs;}
function classify(fragments,pairs){const byId=new Map(fragments.map(item=>[item.id,item]));for(const item of fragments)item.state=item.state??(item.explicit===true?'EXPLICIT':'UNRESOLVED');for(const item of fragments)if(item.type==='BACKGROUND_CLUE')item.state='CONTEXTUAL';return pairs.map(pair=>{const from=byId.get(pair.fromId),to=byId.get(pair.toId);let state='UNRESOLVED';if(from?.state==='EXPLICIT'&&to?.state==='EXPLICIT')state='EXPLICIT';else if(from?.state==='CONTEXTUAL'||to?.state==='CONTEXTUAL'||pair.relation.startsWith('contextual_'))state='CONTEXTUAL';return{...pair,state};});}
function stabilityFor(fragments,connections){const explicit=uniqueByType(fragments.filter(item=>item.state==='EXPLICIT')).reduce((sum,item)=>sum+(CH2_DATA_PROFILE_BALANCE.EXPLICIT[item.type]??0),0);const completed=connections.filter(item=>item.state==='EXPLICIT').reduce((sum,item)=>sum+(CH2_DATA_PROFILE_BALANCE.COMPLETED_CONNECTION[keyFor(item.fromType,item.toType)]??0),0);const contextual=connections.filter(item=>item.state==='CONTEXTUAL').length*CH2_DATA_PROFILE_BALANCE.CONTEXTUAL_CONNECTION;const final=Math.max(CH2_DATA_PROFILE_BALANCE.MIN_PROFILE_STABILITY,Math.min(CH2_DATA_PROFILE_BALANCE.MAX_PROFILE_STABILITY,CH2_DATA_PROFILE_BALANCE.BASE_STABILITY+explicit+completed+contextual));return{base:CH2_DATA_PROFILE_BALANCE.BASE_STABILITY,explicit,completed,contextual,final};}

export function buildNullBossSemanticPlan(snapshot,resolved={fragments:[]}){const fragments=normalizeFragments(snapshot,resolved);addUnresolved(fragments,'PHOTO','unresolved.photo');if(!fragments.some(item=>item.type==='LOCATION'&&item.explicit))addUnresolved(fragments,'LOCATION','unresolved.location');if(!fragments.some(item=>item.type==='TAG'&&item.explicit))addUnresolved(fragments,'TAG','unresolved.tag');const pairs=resolveConnections(fragments,snapshot);const connections=classify(fragments,pairs);const stability=stabilityFor(fragments,connections);const ordered=[...fragments].sort((a,b)=>(PRIORITY.indexOf(a.type)-PRIORITY.indexOf(b.type))||(a.id.localeCompare(b.id)));const usable=ordered.filter(item=>item.state!=='UNRESOLVED'),unresolved=ordered.filter(item=>item.state==='UNRESOLVED');const round1=[...usable.slice(0,4),...unresolved.slice(0,Math.max(0,3-usable.length))].slice(0,5);const round2=[...usable,...unresolved].slice(0,8);while(round2.length<Math.min(3,ordered.length))round2.push(ordered[round2.length]);return{version:2,fragmentStates:Object.fromEntries(ordered.map(item=>[item.id,item.state])),explicitFragments:ordered.filter(item=>item.state==='EXPLICIT').map(item=>item.id),contextualFragments:ordered.filter(item=>item.state==='CONTEXTUAL').map(item=>item.id),unresolvedNodes:unresolved.map(item=>item.id),round1,round2,pairs:connections,connections,profileMaxStability:stability.final,stability,profileLabel:'輪廓穩定度',balance:CH2_DATA_PROFILE_BALANCE};}
