const LABELS={STORY:'限時內容',POST:'貼文',CURRENT_LOCATION:'目前位置',GENERAL_AREA:'大致區域',NO_LOCATION:'不顯示位置',SHARE_NOW:'現在發布',SHARE_LATER:'稍後發布',PUBLIC:'公開',FRIENDS:'朋友',SELECTED:'特定對象',PRIVATE:'僅自己'};
const FRIEND_GROUPS=['Close Friend','Classmate','Old Classmate','Club Member','Event Contact','Other Contact'];

export class EchoView {
  constructor(root){this.root=root;this.screen=root.querySelector('#echo-screen');this.photo=root.querySelector('#echo-photo');this.photoFallback=root.querySelector('#echo-photo-fallback');this.caption=root.querySelector('#echo-caption');this.mode=root.querySelector('#echo-mode');this.title=root.querySelector('#echo-title');this.form=root.querySelector('#echo-form');this.notice=root.querySelector('#echo-notification');this.sessionId=null;this.stage='preview';this.openSetting=null;}
  open(session,handlers){
    if(this.sessionId!==session.id){this.sessionId=session.id;this.stage='preview';this.openSetting=null;}
    this.root.querySelectorAll('#title-screen,#dialogue-scene,#battle-screen,#puzzle-screen,#memory-investigation-screen,#reflection-screen,#chapter-summary-screen').forEach((node)=>node.hidden=true);
    this.screen.hidden=false;this.mode.textContent=`${LABELS[session.mode]} · ECHO`;if(document.activeElement!==this.caption)this.caption.value=session.caption;this.caption.oninput=()=>handlers.onCaption(this.caption.value);this.#photo(session.photo);this.#renderStage(session,handlers);
    this.screen.querySelectorAll('[data-echo-action="close"]').forEach((button)=>button.onclick=handlers.onClose);
    this.screen.querySelector('[data-echo-action="next"]').onclick=()=>{this.stage='compose';this.#renderStage(session,handlers);};
    this.screen.querySelector('[data-echo-action="post"]').onclick=handlers.onPost;
    const save=this.screen.querySelector('[data-echo-action="save"]');save.hidden=!session.allowSave;save.onclick=handlers.onSave;
  }
  close(){this.screen.hidden=true;this.photo.removeAttribute('src');this.form.replaceChildren();this.notice.hidden=true;this.sessionId=null;this.stage='preview';this.openSetting=null;}
  notify(message){this.notice.textContent=message;this.notice.hidden=!message;}
  #photo(photo){this.photo.hidden=!photo?.src;this.photoFallback.hidden=Boolean(photo?.src);if(photo?.src){this.photo.src=photo.src;this.photo.alt=photo.alt;}else this.photoFallback.textContent=photo?.id?`${photo.id}\n照片素材尚未接入`:'尚未選擇照片';}
  #renderStage(session,handlers){
    const preview=this.stage==='preview';this.screen.dataset.echoStage=this.stage;this.title.textContent=preview?'照片預覽':'新貼文';
    this.screen.querySelector('[data-echo-action="next"]').hidden=!preview;this.screen.querySelector('.echo-compose').hidden=preview;this.screen.querySelector('.echo-actions').hidden=preview;this.screen.querySelector('.echo-bottom-nav').hidden=preview;
    if(preview){this.form.replaceChildren();return;}
    const tagLabel=session.taggedCharacters.length?session.taggedCharacters.map((id)=>session.taggableCharacters.find((item)=>item.id===id)?.label??id).join('、'):'尚未標註';
    this.form.replaceChildren(this.#settingRow('標註人物','tag',tagLabel,this.#tagSelector(session,handlers),session.controls.tag),this.#settingRow('新增位置','location',LABELS[session.location],this.#selector('選擇位置','location',['CURRENT_LOCATION','GENERAL_AREA','NO_LOCATION'],session,handlers),session.controls.location),this.#settingRow('分享對象','audience',LABELS[session.audience],this.#selector('選擇分享對象','audience',['PUBLIC','FRIENDS','SELECTED','PRIVATE'],session,handlers),session.controls.audience),this.#settingRow('其他設定','timing',LABELS[session.timing],this.#selector('發布時間','timing',['SHARE_NOW','SHARE_LATER'],session,handlers),session.controls.timing));
    if(session.audience==='FRIENDS')this.form.append(this.#friendsPreview());if(session.audience==='SELECTED')this.form.append(this.#selectedAudience(session,handlers));
  }
  #settingRow(title,kind,value,detail,rule={visible:true,enabled:true,locked:false}){const section=document.createElement('section');section.className='echo-setting';section.hidden=rule.visible===false;const button=document.createElement('button');button.type='button';button.className='echo-setting-row';button.disabled=rule.enabled===false||rule.locked||!detail;button.innerHTML=`<span>${title}</span><span><small>${value}</small> ›</span>`;button.setAttribute('aria-expanded',String(this.openSetting===kind));if(detail){detail.hidden=this.openSetting!==kind;button.onclick=()=>{this.openSetting=this.openSetting===kind?null:kind;detail.hidden=this.openSetting!==kind;button.setAttribute('aria-expanded',String(this.openSetting===kind));};}section.append(button);if(detail)section.append(detail);return section;}
  #selector(title,kind,values,session,handlers){const rule=session.controls[kind];const field=document.createElement('fieldset');field.className='echo-selector';field.hidden=!rule.visible;field.disabled=!rule.enabled||rule.locked;const legend=document.createElement('legend');legend.textContent=title;field.append(legend,...values.map((value)=>{const button=document.createElement('button');button.type='button';button.textContent=LABELS[value];button.dataset.echoValue=value;button.setAttribute('aria-pressed',String(session[kind]===value));button.onclick=()=>handlers.onSelect(kind,value);return button;}));return field;}
  #tagSelector(session,handlers){const field=document.createElement('fieldset');field.className='echo-selected-audience echo-tag-selector';const legend=document.createElement('legend');legend.textContent='標記人物';field.append(legend,...session.taggableCharacters.map((character)=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.checked=session.taggedCharacters.includes(character.id);input.onchange=()=>handlers.onToggleTag(character.id);label.append(input,document.createTextNode(character.label??character.id));return label;}));if(!session.taggableCharacters.length){const empty=document.createElement('p');empty.textContent='目前沒有可標記人物。';field.append(empty);}return field;}
  #friendsPreview(){const section=document.createElement('section');section.className='echo-audience-preview';const heading=document.createElement('h3');heading.textContent='這則內容會顯示給朋友';const list=document.createElement('ul');for(const group of FRIEND_GROUPS){const item=document.createElement('li');item.textContent=group;list.append(item);}section.append(heading,list);return section;}
  #selectedAudience(session,handlers){const field=document.createElement('fieldset');field.className='echo-selected-audience';const legend=document.createElement('legend');legend.textContent='選擇觀看對象';field.append(legend,...session.contacts.map((contact)=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.checked=session.selectedAudience.includes(contact.id);input.onchange=()=>handlers.onToggleSelected(contact.id);label.append(input,document.createTextNode(contact.label??contact.id));return label;}));if(!session.contacts.length){const empty=document.createElement('p');empty.textContent='本次事件沒有可選對象。';field.append(empty);}return field;}
}
