export class GuidanceView {
  constructor(root){this.root=root;this.intro=root.querySelector('#story-intro');this.introText=root.querySelector('#story-intro-text');this.introProgress=root.querySelector('#story-intro-progress');this.modal=root.querySelector('#guidance-modal');this.modalTitle=root.querySelector('#guidance-title');this.modalBody=root.querySelector('#guidance-body');this.notice=root.querySelector('#quest-notification');this.noticeTitle=root.querySelector('#quest-notification-title');this.noticeObjective=root.querySelector('#quest-notification-objective');this.noticeTimer=null;}
  openIntro(line,index,total,{onContinue,onSkip}){this.hideGameScreens();this.intro.hidden=false;this.introText.textContent=line;this.introProgress.textContent=`${index+1}／${total}`;this.root.querySelector('#story-intro-continue').onclick=onContinue;this.root.querySelector('#story-intro-skip').onclick=onSkip;}
  closeIntro(){this.intro.hidden=true;}
  hideGameScreens(){['#title-screen','#dialogue-scene','#map-screen','#battle-screen','#puzzle-screen','#memory-investigation-screen','#reflection-screen','#chapter-summary-screen'].forEach((selector)=>{const node=this.root.querySelector(selector);if(node)node.hidden=true;});}
  openControls({battle=false,onClose}){this.root.dataset.guidanceOpen='true';this.modal.hidden=false;this.modal.dataset.panel='controls';this.modalTitle.textContent=battle?'首次戰鬥操作':'操作說明';const touch=this.root.dataset.touchCapable==='true';const exploration=touch?['移動：使用畫面方向控制器','互動：靠近並面向目標後，點擊畫面「互動」按鈕','操作說明與任務清單可由畫面按鈕開啟','對話、解謎與戰鬥皆可直接點擊畫面按鈕']:['移動：方向鍵或 WASD','互動：靠近並面向目標後按 E','操作說明：按 M','任務清單：按 J','對話：Enter 顯示下一句，Space 立即顯示全文'];const items=battle?['每回合從可用的戰鬥指令選擇一項行動。','「攻擊」造成傷害；「觀察」找出線索；「情緒」切換策略並消耗技能值。','PLAYER 行動後由敵方行動，再進入下一回合。']:exploration;this.modalBody.replaceChildren(this.list(items));this.root.querySelector('#guidance-close').onclick=onClose;}
  openJournal(groups,onClose){this.root.dataset.guidanceOpen='true';this.modal.hidden=false;this.modal.dataset.panel='journal';this.modalTitle.textContent='任務與夥伴';const labels={main:'主線任務',side:'支線任務',partners:'認識的夥伴',completed:'已完成'};const fragment=document.createDocumentFragment();for(const key of ['main','side','partners','completed']){const section=document.createElement('section');section.className='quest-group';const heading=document.createElement('h3');heading.textContent=labels[key];section.append(heading);const quests=groups[key]??[];if(!quests.length){const empty=document.createElement('p');empty.className='quest-empty';empty.textContent=key==='partners'?'尚未認識夥伴。':'目前沒有任務。';section.append(empty);}else for(const quest of quests){const article=document.createElement('article');article.className=`quest-entry${quest.partner?' partner-entry':''}`;const title=document.createElement('h4');title.textContent=quest.title;const description=document.createElement('p');description.textContent=quest.description;const objective=document.createElement('p');objective.className='quest-objective';objective.textContent=quest.partner?'關係：已認識':quest.completed?'狀態：已完成':`目前目標：${quest.objective}`;article.append(title,description,objective);section.append(article);}fragment.append(section);}this.modalBody.replaceChildren(fragment);this.root.querySelector('#guidance-close').onclick=onClose;}
  list(items){const list=document.createElement('ul');list.className='guidance-list';for(const text of items){const item=document.createElement('li');item.textContent=text;list.append(item);}return list;}
  closeModal(){this.root.dataset.guidanceOpen='false';this.modal.hidden=true;this.modal.removeAttribute('data-panel');}
  updateQuestHud({mainActive=false,sideActive=false,sideCompleted=false}={}){const button=this.root.querySelector('#quest-hud-button');if(!button)return;button.dataset.mainActive=String(mainActive);button.dataset.sideActive=String(sideActive);button.querySelector('[data-quest-main]').textContent=`主線${mainActive?' ●':''}`;button.querySelector('[data-quest-side]').textContent=`支線${sideActive?' ●':sideCompleted?' ✓':''}`;}
  showNotification(objective){clearTimeout(this.noticeTimer);this.noticeTitle.textContent='任務已更新';this.noticeObjective.textContent=objective;this.notice.hidden=false;requestAnimationFrame(()=>this.notice.classList.add('is-visible'));this.noticeTimer=setTimeout(()=>{this.notice.classList.remove('is-visible');setTimeout(()=>{this.notice.hidden=true;},220);},2600);}
}
