export class PuzzleView {
  constructor(root){this.root=root;this.screen=root.querySelector('#puzzle-screen');this.title=root.querySelector('#puzzle-title');this.instructions=root.querySelector('#puzzle-instructions');this.hotspots=root.querySelector('#photo-hotspots');this.feedback=root.querySelector('#puzzle-feedback');this.progress=root.querySelector('#puzzle-progress');this.image=root.querySelector('#inspection-photo');this.caption=root.querySelector('#inspection-caption');}
  show(){this.root.querySelector('#title-screen').hidden=true;this.root.querySelector('#map-screen').hidden=true;this.screen.hidden=false;}
  open(puzzle,selected,onToggle){this.show();this.screen.classList.remove('puzzle-screen--inspection');this.title.textContent=puzzle.displayName;this.instructions.textContent=puzzle.instructions;this.feedback.textContent='請選擇所有可能透露資訊的線索。';this.feedback.className='puzzle-feedback';this.image.hidden=true;this.caption.hidden=true;this.renderHotspots(puzzle,selected,onToggle);this.buttons('確認線索','重新檢查','返回探索地圖',false);}
  openPhotoInspection(puzzle,index,selected,onToggle,feedback=''){this.show();this.screen.classList.add('puzzle-screen--inspection');this.title.textContent=puzzle.displayName;this.instructions.textContent=puzzle.instructions;const photo=puzzle.photos[index];this.image.src=photo.image;this.image.alt=photo.alt;this.image.style.objectPosition=photo.objectPosition??'center';this.image.hidden=false;this.caption.hidden=false;this.caption.textContent=`${photo.id}｜${photo.title}`;this.feedback.textContent=feedback||'RIN：「你覺得這張照片有什麼需要注意的地方嗎？」';this.feedback.className='puzzle-feedback';this.renderPhotoOptions(puzzle,index,selected,onToggle);this.buttons(index===puzzle.photos.length-1?'完成檢查':'下一張照片','重新開始','稍後繼續',false);}
  renderHotspots(puzzle,selected,onToggle){this.hotspots.replaceChildren(...puzzle.hotspots.map((spot,index)=>{const button=document.createElement('button');button.type='button';button.className=`photo-hotspot photo-hotspot--${index+1}`;button.dataset.hotspot=spot.id;button.setAttribute('aria-pressed',String(selected.has(spot.id)));button.innerHTML=`<strong>${spot.label}</strong><span>${spot.explanation}</span>`;button.addEventListener('click',()=>onToggle(spot.id));return button;}));this.progress.textContent=`已發現 ${selected.size}／${puzzle.required.length}`;}
  renderPhotoOptions(puzzle,index,selected,onToggle){const photo=puzzle.photos[index];this.hotspots.replaceChildren(...puzzle.options.map((option)=>{const button=document.createElement('button');button.type='button';button.className='photo-inspection-option';button.setAttribute('aria-pressed',String(selected.has(option.id)));button.textContent=option.label;button.addEventListener('click',()=>onToggle(option.id));return button;}));this.progress.textContent=`照片 ${index+1}／${puzzle.photos.length}｜${photo.title}`;}
  showPhotoFeedback(text,answers=[],exact=false,isLast=false){this.feedback.textContent=`${exact?'選得很完整。':'可以再留意：'} 正確答案：${answers.join('、')}。 RIN：「${text}」`;this.feedback.className='puzzle-feedback is-success';this.root.querySelector('#puzzle-submit').textContent=isLast?'完成檢查':'下一張照片';}
  showPhotoPrompt(text){this.feedback.textContent=text;this.feedback.className='puzzle-feedback';}
  showPhotoComplete(){this.feedback.textContent='八張照片都看完了，回去和 RIN 說說吧。';this.feedback.className='puzzle-feedback is-success';this.buttons('檢查完成','重新開始','返回 RIN',true);}
  buttons(submit,retry,exit,submitDisabled){const submitButton=this.root.querySelector('#puzzle-submit');const retryButton=this.root.querySelector('#puzzle-retry');const exitButton=this.root.querySelector('#puzzle-exit');submitButton.textContent=submit;submitButton.disabled=submitDisabled;retryButton.textContent=retry;retryButton.hidden=false;exitButton.textContent=exit;}
  showFailure(missing){this.feedback.textContent=`還有 ${missing} 個線索尚未發現，可以繼續檢查或重試。`;this.feedback.className='puzzle-feedback is-error';}
  showSuccess(modifiers){this.feedback.textContent=`檢查完成！戰鬥優勢：${modifiers.map((item)=>item.displayName).join('、')}`;this.feedback.className='puzzle-feedback is-success';this.root.querySelector('#puzzle-submit').disabled=true;}
  reset(){this.root.querySelector('#puzzle-submit').disabled=false;this.root.querySelector('#puzzle-retry').hidden=false;}
  close(){this.screen.hidden=true;this.screen.classList.remove('puzzle-screen--inspection');}
}
