import { AUDIO_ASSETS, BGM_ASSETS, SFX_FALLBACKS, SFX_OPTIONS } from './AudioAssets.js?v=bgm2';

const SETTINGS_KEY='nullPrivacyRpg.audio.v1';
export class AudioManager{
  constructor(storage=globalThis.localStorage??{getItem(){return null;},setItem(){}}){this.storage=storage;this.context=null;this.active=new Set();this.lastPlayed=new Map();this.timers=new Set();this.maxActive=8;this.bgmAudio=null;this.currentBGM=null;this.currentBGMPath=null;this.bgmFadeTimer=null;this.settings={bgmVolume:.38,sfxVolume:.18,muted:false,bgmMuted:false,sfxMuted:false,reducedEffects:false,...this.load()};}
  load(){try{return JSON.parse(this.storage.getItem(SETTINGS_KEY)??'{}');}catch{return {};}}
  save(){this.storage.setItem(SETTINGS_KEY,JSON.stringify(this.settings));}
  setSFXVolume(value){this.settings.sfxVolume=Math.max(0,Math.min(1,Number(value)));this.save();}
  setBGMVolume(value){this.settings.bgmVolume=Math.max(0,Math.min(1,Number(value)));this.applyBGMVolume();this.save();}
  setMute(value){this.settings.muted=Boolean(value);this.applyBGMVolume();if(this.settings.muted){for(const source of this.active){try{source.stop?.();source.pause?.();}catch{}}this.active.clear();}this.updateMuteUI?.();this.save();}
  setBGMMute(value){this.settings.bgmMuted=Boolean(value);this.applyBGMVolume();this.save();}
  setSFXMute(value){this.settings.sfxMuted=Boolean(value);this.save();}
  setReducedEffects(value){this.settings.reducedEffects=Boolean(value);globalThis.document?.documentElement.classList.toggle('reduced-effects',this.settings.reducedEffects);this.save();}
  bindSettings(root){const mute=root.querySelector('#audio-mute'),quickMute=root.querySelector('#audio-mute-toggle'),bgmMute=root.querySelector('#bgm-mute'),sfxMute=root.querySelector('#sfx-mute'),reduced=root.querySelector('#reduced-effects'),sfxVolume=root.querySelector('#sfx-volume'),bgmVolume=root.querySelector('#bgm-volume');this.updateMuteUI=()=>{if(mute)mute.checked=this.settings.muted;if(quickMute){quickMute.setAttribute('aria-pressed',String(this.settings.muted));quickMute.setAttribute('aria-label',this.settings.muted?'取消全部靜音':'全部靜音');quickMute.textContent=this.settings.muted?'🔇 取消靜音':'🔊 靜音';}};if(mute)mute.addEventListener('change',()=>this.setMute(mute.checked));if(quickMute)quickMute.addEventListener('click',()=>this.setMute(!this.settings.muted));if(bgmMute){bgmMute.checked=this.settings.bgmMuted;bgmMute.addEventListener('change',()=>this.setBGMMute(bgmMute.checked));}if(sfxMute){sfxMute.checked=this.settings.sfxMuted;sfxMute.addEventListener('change',()=>this.setSFXMute(sfxMute.checked));}if(reduced){reduced.checked=this.settings.reducedEffects;reduced.addEventListener('change',()=>this.setReducedEffects(reduced.checked));}if(sfxVolume){sfxVolume.value=String(Math.round(this.settings.sfxVolume*100));sfxVolume.addEventListener('input',()=>this.setSFXVolume(Number(sfxVolume.value)/100));}if(bgmVolume){bgmVolume.value=String(Math.round(this.settings.bgmVolume*100));bgmVolume.addEventListener('input',()=>this.setBGMVolume(Number(bgmVolume.value)/100));}this.updateMuteUI();this.setReducedEffects(this.settings.reducedEffects);}
  targetBGMVolume(){return this.settings.muted||this.settings.bgmMuted?0:this.settings.bgmVolume;}
  applyBGMVolume(){if(this.bgmAudio)this.bgmAudio.volume=this.targetBGMVolume();}
  playBGM(id,{fade=700}={}){const path=BGM_ASSETS[id];if(!path){console.warn(`Missing BGM Asset: ${id}`);return false;}if(this.bgmAudio&&this.currentBGMPath===path){this.currentBGM=id;this.resumeBGM();return true;}if(typeof Audio==='undefined')return false;const next=new Audio(path);next.loop=true;next.preload='auto';next.volume=0;next.addEventListener('error',()=>console.warn(`Missing BGM Asset: ${id}`),{once:true});const previous=this.bgmAudio;this.bgmAudio=next;this.currentBGM=id;this.currentBGMPath=path;next.play().then(()=>this.fadeTo(next,this.targetBGMVolume(),fade)).catch(()=>{});if(previous)this.fadeTo(previous,0,fade,()=>{previous.pause();previous.removeAttribute('src');});return true;}
  fadeTo(audio,target,duration=700,onDone=null){if(!audio)return;if(duration<=0){audio.volume=Math.max(0,Math.min(1,target));onDone?.();return;}const start=audio.volume,steps=Math.max(1,Math.round(duration/50)),delta=(target-start)/steps;let count=0;const timer=setInterval(()=>{count++;audio.volume=Math.max(0,Math.min(1,start+delta*count));if(count>=steps){clearInterval(timer);this.timers.delete(timer);onDone?.();}},50);this.timers.add(timer);}
  stopBGM({fade=500}={}){const audio=this.bgmAudio;if(!audio)return;this.bgmAudio=null;this.currentBGM=null;this.currentBGMPath=null;this.fadeTo(audio,0,fade,()=>audio.pause());}
  pauseBGM(){this.bgmAudio?.pause();}
  resumeBGM(){if(!this.bgmAudio||this.settings.muted||this.settings.bgmMuted)return false;this.applyBGMVolume();this.bgmAudio.play().catch(()=>{});return true;}
  playSFX(id,{delay=0,volume=1}={}){if(delay){const timer=setTimeout(()=>{this.timers.delete(timer);this.playSFX(id,{volume});},delay);this.timers.add(timer);return true;}if(this.settings.muted||this.settings.sfxMuted||this.settings.sfxVolume<=0)return false;const option=SFX_OPTIONS[id]??{},now=performance.now(),last=this.lastPlayed.get(id)??-Infinity;if(now-last<(option.cooldown??90)||this.active.size>=this.maxActive)return false;this.lastPlayed.set(id,now);const level=Math.max(0,Math.min(1,(option.volume??1)*volume));const asset=AUDIO_ASSETS[id];if(asset)return this.playFile(asset,level,id);return this.playFallback(id,level);}
  playFile(path,level=1,id=''){const audio=new Audio(path);audio.volume=Math.min(1,this.settings.sfxVolume*level);this.active.add(audio);let settled=false;const release=()=>{if(settled)return false;settled=true;this.active.delete(audio);return true;};const fail=()=>{if(release())this.playFallback(id,level);};audio.addEventListener('ended',release,{once:true});audio.addEventListener('error',fail,{once:true});audio.play().catch(fail);return true;}
  playFallback(id,level=1){const preset=SFX_FALLBACKS[id];if(!preset)return false;const AudioContext=window.AudioContext??window.webkitAudioContext;if(!AudioContext)return false;this.context??=new AudioContext();if(this.context.state==='suspended')this.context.resume().catch(()=>{});const [frequency,duration,type]=preset,osc=this.context.createOscillator(),gain=this.context.createGain(),start=this.context.currentTime;osc.type=type;osc.frequency.setValueAtTime(frequency,start);osc.frequency.exponentialRampToValueAtTime(Math.max(40,frequency*.72),start+duration);gain.gain.setValueAtTime(this.settings.sfxVolume*level,start);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain).connect(this.context.destination);this.active.add(osc);osc.addEventListener('ended',()=>this.active.delete(osc),{once:true});osc.start(start);osc.stop(start+duration);return true;}
  stopAll(){for(const timer of this.timers){clearTimeout(timer);clearInterval(timer);}this.timers.clear();this.stopBGM({fade:0});for(const source of this.active){try{source.stop?.();source.pause?.();}catch{}}this.active.clear();}
}
